### PR TITLE
Update for HasRep with better GADT support.

### LINKED ISSUE #65: Conflicting family instance declarations
I have an (internal,) inductive GADT for which I am trying to derive (or write) `HasRep` and `TargetOb` instances.  Deriving HasRep fails for clear reasons, however, it's not clear how the correct instance could be written:

```haskell
data Foo a where
  FooNat :: Natural -> Foo Natural
  FooIsEven :: Natural -> Foo Bool
  FooBar :: Bar a -> Foo a
  FooBaz :: Baz a -> Foo a

data Bar a where
  BarNone :: Bar Word64
  SomeBazIsTrue :: Some Baz -> Bar Bool

data Baz a where
  Inductive :: Foo a -> Baz a

deriveHasRep ''Baz
deriveHasRep ''Bar
deriveHasRep ''Foo
```

This generates the following `Rep` type instaces for `Foo` which obviously overlap:

```haskell
Rep (Foo Bool) = Natural
Rep (Foo a) = Either (Bar a) (Baz a)
 ```

However, it seems like these mutually inductive GADTS could be encoded if there was type family dependency on `Rep` such that we could ensure that there is only ever one instance for each concrete type of the index plus the polymorphic (inductive) index.  Maybe something like `type Rep a = r | r -> a` as outlined [here](https://stackoverflow.com/questions/46206079/associated-data-families-and-overlapping-instances).  

Would something like this work?

### PR DESCRIPTION
**Pull request by sellout**
Fixes #65.

### CODE REVIEW

**Comment by o1lo01ol1o** [comment]
@sellout I finally got a chance to look at this again but I ran into an overlapping instances problem locally. 

When I try to replicate the problem against the the examples here, using [cdd51e5](https://github.com/con-kitty/categorifier-c/pull/66/commits/cdd51e5830eb46c98b9ceb2b4dbb8d33219554f6), I run into a few problems:
in nix-shell, cabal complains:

```
$ cabal build all
fatal: reference is not a tree: 949ced997a600168205e4ad9d2f1425ccd3dc622
```

If I update `concat` to the most recent hash and rebuild, I'm then able to build the project but `unconcat` fails with, among other things, 
```haskell
Categorifier/C/UnconCat.hs:33:20: error:
    • Couldn't match expected type ‘t2
                                    -> categorifier-duoids-0.1:Categorifier.Duoidal.Parallel
                                         (ExceptT
                                            (GHC.Base.NonEmpty
                                               Categorifier.Core.Types.MissingSymbol)
                                            Plugins.CoreM)
                                         Plugins.TyCon’
                  with actual type ‘categorifier-duoids-0.1:Categorifier.Duoidal.Parallel
                                      (ExceptT
                                         (GHC.Base.NonEmpty Categorifier.Core.Types.MissingSymbol)
                                         Plugins.CoreM)
                                      Plugins.TyCon’
    • The function ‘findTyCon’ is applied to two arguments,
      but its type ‘template-haskell-2.16.0.0:Language.Haskell.TH.Syntax.Name
                    -> categorifier-duoids-0.1:Categorifier.Duoidal.Parallel
                         (ExceptT
                            (GHC.Base.NonEmpty Categorifier.Core.Types.MissingSymbol)
                            Plugins.CoreM)
                         Plugins.TyCon’
      has only one
      In a stmt of a 'do' block:
        targetObTyCon <- findTyCon
                           "Categorifier.C.CExpr.Cat.TargetOb" "TargetOb"
      In the expression:
        do catId <- findId "Categorifier.C.CExpr.Cat" "cat"
           cexprTyCon <- findTyCon "Categorifier.C.CExpr.Types.Core" "CExpr"
           targetObTyCon <- findTyCon
                              "Categorifier.C.CExpr.Cat.TargetOb" "TargetOb"
           return \ buildDictionary cat nativeFunTy target args
                    -> runMaybeT $ do ...
   |
33 |   targetObTyCon <- findTyCon "Categorifier.C.CExpr.Cat.TargetOb" "TargetOb"

```

**Comment by sellout** [comment]
@o1lo01ol1o Sorry, I accidentally force-pushed a change and broke that reference. Let me get it cleaned up.

**Comment by sellout** [comment]
@o1lo01ol1o This should be better now. And hopefully merged into master soon (but would appreciate your feedback if you try it before then).

**Review by zliu41 — APPROVED** [review]
:+1:

**Pull request merged**
